=== xxMikhailx/Orangery_XML-XSD/data/orangery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        xmlns:tns="http://www.example.com/flowers"
        elementFormDefault="qualified">

    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:flower" minOccurs="2" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Flower">
    <sequence>
        <element name="name" type="string" />
        <element name="origin" type="string" />
        <element name="visual-parameters" type="tns:Visual" />
    </sequence>
    <attribute name="id" use="required">
        <simpleType>
            <restriction base="ID">
                <pattern value="([a-z])[0-9]{1,3}" />
            </restriction>
        </simpleType>
    </attribute>
    </complexType>

    <complexType name="GardenFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="growing-tips" type="tns:Growing" />
                    <element name="multiplying" type="tns:Multiplying" />
                </sequence>
                <attribute name="soil" use="optional" default="dirt">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="dirt"></enumeration>
                            <enumeration value="podzolic"></enumeration>
                            <enumeration value="sod-podzolic"></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="CutFlower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="price" type="tns:Price"></element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Visual">
        <sequence>
            <element name="stem-color" type="string" />
            <element name="leaf-color" type="string" />
            <element name="plant-size" type="integer" />
        </sequence>
    </complexType>

    <complexType name="Growing">
        <sequence>
            <element name="temperature" type="tns:Temperature" />
            <element name="watering" type="integer" />
        </sequence>
    </complexType>

    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="leaf"></enumeration>
            <enumeration value="stalk"></enumeration>
            <enumeration value="seed"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="Temperature">
        <restriction base="integer">
            <minInclusive value="-50"></minInclusive>
            <maxInclusive value="60"></maxInclusive>
        </restriction>
    </simpleType>

    <simpleType name="Price">
        <restriction base="integer">
            <minInclusive value="0"></minInclusive>
        </restriction>
    </simpleType>

    <element name="flower" type="tns:Flower" abstract="true" />
    <element name="cut-flower" type="tns:CutFlower" substitutionGroup="tns:flower" />
    <element name="garden-flower" type="tns:GardenFlower" substitutionGroup="tns:flower" />

</schema>

=== xxMikhailx/Orangery_XML-XSD/data/orangery.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/flowers"
         xsi:schemaLocation="http://www.example.com/flowers orangery.xsd">

    <garden-flower id="g1" soil="podzolic">
        <name>Rose</name>
        <origin>Holland</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Red</leaf-color>
            <plant-size>60</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <watering>80</watering>
        </growing-tips>
        <multiplying>stalk</multiplying>
    </garden-flower>

    <garden-flower id="g2" soil="dirt">
        <name>Thoren</name>
        <origin>Asia</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Violet</leaf-color>
            <plant-size>30</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>22</temperature>
            <watering>60</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
    </garden-flower>

    <garden-flower id="g3" soil="sod-podzolic">
        <name>Kermek</name>
        <origin>Central Asia</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Blue</leaf-color>
            <plant-size>40</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>18</temperature>
            <watering>10</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
    </garden-flower>

    <garden-flower id="g4" soil="dirt">
        <name>Abelia</name>
        <origin>Japan</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Pink</leaf-color>
            <plant-size>150</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>16</temperature>
            <watering>70</watering>
        </growing-tips>
        <multiplying>stalk</multiplying>
    </garden-flower>

    <garden-flower id="g5" soil="podzolic">
        <name>Impatiens</name>
        <origin>Africa</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Pink</leaf-color>
            <plant-size>30</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>21</temperature>
            <watering>170</watering>
        </growing-tips>
        <multiplying>stalk</multiplying>
    </garden-flower>

    <garden-flower id="g6" soil="sod-podzolic">
        <name>Vallota</name>
        <origin>South Africa</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Red</leaf-color>
            <plant-size>60</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25</temperature>
            <watering>90</watering>
        </growing-tips>
        <multiplying>seed</multiplying>
    </garden-flower>

    <garden-flower id="g7" soil="dirt">
        <name>Hedychium</name>
        <origin>South Asia</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Yellow</leaf-color>
            <plant-size>45</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>27</temperature>
            <watering>105</watering>
        </growing-tips>
        <multiplying>leaf</multiplying>
    </garden-flower>

    <garden-flower id="g8" soil="dirt">
        <name>Jasminum</name>
        <origin>China</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>190</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>19</temperature>
            <watering>85</watering>
        </growing-tips>
        <multiplying>stalk</multiplying>
    </garden-flower>

    <cut-flower id="f1">
        <name>Iris</name>
        <origin>Holland</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>40</plant-size>
        </visual-parameters>
        <price>60000</price>
    </cut-flower>

    <cut-flower id="f2">
        <name>Gerbera</name>
        <origin>Holland</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Red</leaf-color>
            <plant-size>60</plant-size>
        </visual-parameters>
        <price>40000</price>
    </cut-flower>

    <cut-flower id="f3">
        <name>Tulip</name>
        <origin>Iran</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Yellow</leaf-color>
            <plant-size>30</plant-size>
        </visual-parameters>
        <price>30000</price>
    </cut-flower>

    <cut-flower id="f4">
        <name>Chrysanthemum</name>
        <origin>Asia</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>55</plant-size>
        </visual-parameters>
        <price>45000</price>
    </cut-flower>

    <cut-flower id="f5">
        <name>Lily</name>
        <origin>Greece</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>90</plant-size>
        </visual-parameters>
        <price>95000</price>
    </cut-flower>

    <cut-flower id="f6">
        <name>Clove</name>
        <origin>Germany</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Red</leaf-color>
            <plant-size>70</plant-size>
        </visual-parameters>
        <price>15000</price>
    </cut-flower>

    <cut-flower id="f7">
        <name>Peony</name>
        <origin>Greece</origin>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>75</plant-size>
        </visual-parameters>
        <price>60000</price>
    </cut-flower>

</flowers>
